name: 02 - Docker Build & Trivy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker-build-trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t devsecops-demo:${{ github.sha }} .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: devsecops-demo:${{ github.sha }}
          format: table
          exit-code: "1"
          severity: HIGH,CRITICAL